runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: MySQLdb
  version: "latest"

default_expiration: "0d 1m"

handlers:

- url: /sql/(.*)
  script: sql.\1.app

- url: /$
  static_files: www/index.html
  upload: www/index.html
  secure: always


- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  secure: always  

# https://cloud.google.com/appengine/docs/flexible/python/using-cloud-sql
# For SQL_ALCHEMY 
beta_settings:
    cloud_sql_instances: votedb-216400:us-central1:votedb-a
#    enable_app_engine_apis: true


# [START gae_python_mysql_env]
env_variables:
    CLOUDSQL_CONNECTION_NAME: votedb-216400:us-central1:votedb-a
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: theusual

    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://root:theusual@/voter?unix_socket=/cloudsql/votedb-216400:us-central1:votedb-a

# [END gae_python_mysql_env]

