runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /$
  static_files: www/index.html
  upload: www/index.html

- url: /sql/test
  script: sql.test.app
  secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  secure: always  

libraries:
- name: MySQLdb
  version: "latest"

# [START gae_python_mysql_env]
env_variables:
    CLOUDSQL_CONNECTION_NAME: votedb-216400:us-central1:votedb-a
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: theusual

# [END gae_python_mysql_env]

